married(george,mum).
married(spencer,kydd).
married(philip,elizabeth).
married(charles,diana).
married(mark,anne).
married(andrew,sarah).
female(mum).
female(kydd).
female(elizabeth).
female(margaret).
female(diana).
female(anne).
female(sarah).
female(zara).
female(beatrice).
female(eugenie).
son(elizabeth,charles).
son(philip,charles).
son(elizabeth,andrew).
son(philip,andrew).
son(elizabeth,edward).
son(philip,edward).
son(diana,william).
son(charles,william).
son(diana,harry).
son(charles,harry).
son(anne,peter).
son(mark,peter).
daughter(george,elizabeth).
daughter(mum,elizabeth).
daughter(george,margaret).
daughter(mum,margaret).
daughter(spencer,diana).
daughter(kydd,diana).
daughter(elizabeth,anne).
daughter(philip,anne).
daughter(anne,zara).
daughter(mark,zara).
daughter(andrew,beatrice).
daughter(sarah,beatrice).
daughter(andrew,eugenie).
daughter(sarah,eugenie).

wife(X,Z):-married(X,Z), female(Z).