wife(george,mum).
wife(spencer,kydd).
wife(philip,elizabeth).
wife(charles,diana).
wife(mark,anne).
wife(andrew,sarah).

son(elizabeth,andrew).
son(philip,andrew).
son(elizabeth,charles).
son(philip,charles).
son(elizabeth,edward).
son(philip,edward).
son(diana,william).
son(charles,william).
son(diana,harry).
son(charles,harry).
son(anne,peter).
son(mark,peter).

daughter(george,elizabeth).
daughter(mum,elizabeth).
daughter(george,margaret).
daughter(mum,margaret).
daughter(spencer,diana).
daughter(kydd,diana).
daughter(elizabeth,anne).
daughter(philip,anne).
daughter(anne,zara).
daughter(mark,zara).
daughter(andrew,beatrice).
daughter(sarah,beatrice).
daughter(andrew,eugenie).
daughter(sarah,eugenie).

husband(X,Y):-wife(X,Y).
spouse(X,Y):-wife(X,Y).
child(X,W):-((son(X,W));(daughter(X,W))).
parent(X,W):-son(W,X);daughter(W,X).
grandChild(X,W):-child(X,A),child(A,W).
greatGrandParent(X,W):-parent(X,A),parent(A,B),parent(B,W).
brother(X,W):-parent(X,A),husband(A,B),son(B,W),not(X=W).
sister(X,W):-parent(X,A),husband(A,B),daughter(B,W),not(X=W).
aunt(X,W):-parent(X,A),sister(A,W).
uncle(X,W):-parent(X,A),brother(A,W).
brotherInLaw(X,W):-(husband(A,X),brother(A,W);(wife(X,B),brother(B,W));(sister(X,C),husband(C,W))).
sisterInLaw(X,W):-(wife(X,A),sister(A,W));(husband(B,X),sister(B,W));(brother(X,C),wife(C,W)).
firstCousin(X,W):-parent(X,A),(sister(A,B),child(B,W);brother(A,C),child(C,W)).